# Generated by Django 4.1 on 2022-09-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slide',
            table='slide',
        ),
    ]
