# Generated by Django 5.1.1 on 2024-09-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={"verbose_name": "班级", "verbose_name_plural": "班级名称"},
        ),
        migrations.AlterModelTable(
            name="grade",
            table="grade",
        ),
    ]
