# Generated by Django 5.1.1 on 2024-09-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0002_alter_grade_options_alter_grade_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="grade_number",
            field=models.CharField(max_length=20, unique=True, verbose_name="班级编号"),
        ),
    ]
