# Generated by Django 5.1.1 on 2024-09-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(max_length=50, verbose_name="老师姓名"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="手机号码"
                    ),
                ),
                ("gender", models.CharField(max_length=1, verbose_name="性别")),
                ("birthday", models.DateField(verbose_name="出生日期")),
            ],
            options={
                "verbose_name": "教师",
                "verbose_name_plural": "教师信息",
                "db_table": "teacher",
            },
        ),
    ]
