# Generated by Django 5.1.1 on 2024-09-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "avatar",
                    models.ImageField(
                        help_text="最佳尺寸为800.*600",
                        upload_to="avator",
                        verbose_name="头像",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="人物名称", max_length=200, verbose_name="姓名"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="人物职务", max_length=200, verbose_name="职务"
                    ),
                ),
                ("rank", models.IntegerField(verbose_name="排序")),
            ],
            options={
                "verbose_name": "团队管理",
                "verbose_name_plural": "团队人物信息管理",
                "db_table": "team",
            },
        ),
    ]
